# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d1c36f79b38bf0411cad38f2cf5704ad13fb865b0d881d73cdf5938afe68415ca160009c5ebf9e5a78e095934a88346ec737e5f3ad0cd5dd99eff25a3267e6e

test:
  secret_key_base: 7a79594c788c44355158a73f6e8491f5169212ac600d890dc652fe04c76bd74c806b73b83e1108e8d818147b698abb2933e58548c51608f756665a3565bcc82b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
